### PR TITLE
Correct the variable name in verify.sh

### PR DESCRIPTION
**Pull request by willwillhi1**
Replace 'plot_rc' with 'final_ret'.

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
Use `git rebase` and improve the git commit message.

**Comment by willwillhi1** [comment]
Is it okay to use the following commit message?    

Subject:
Fix exit code name typo
Body:
Replace 'plot_rc' with 'final_ret'.

**Comment by jserv** [comment]
> Is it okay to use the following commit message?
> Subject: Fix exit code name typo Body: Replace 'plot_rc' with 'final_ret'.

Simply write "scripts: Correct the variable name to capture exit code"
In the commit message body, you can mention the potential problem you have suffered.

**Comment by willwillhi1** [comment]
Can it be changed to the following?

Subject:
Correct variable name to capture exit code
Body:
'plot_rc' does not represent the exit code, it should be changed to 
'final_ret', so that the correct exit code can be obtained.

**Comment by jserv** [comment]
> Can it be changed to the following?

You should amend git commit messages and force-push. Then, let's review. Talk is cheap. Show me the code.

**Comment by jserv** [comment]
Don't use `git merge`. Instead, use the following:
```shell
git remote add upstream https://github.com/sysprog21
git fetch upstream
git rebase upstream/main
git push --force
```

**Comment by jserv** [comment]
Thank @willwillhi1 for contributing!

**Pull request merged**
